In [5]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd 
from time import sleep
import time

In [6]:
def connect_to_linkedin ():
    driver.get("https://www.linkedin.com/checkpoint/lg/sign-in-another-account")
    time.sleep(5)
    username = driver.find_element_by_id("username")
    username.send_keys("chiheb.jamazi@esprit.tn")
    pword = driver.find_element_by_id("password")
    pword.send_keys("Seawaymn2011&&")
    driver.find_element_by_xpath("//button[@type='submit']").click()

In [7]:
def scrolling_function ():
    SCROLL_PAUSE_TIME = 1.5
    # Get scroll height
    last_height = driver.execute_script("return document.body.scrollHeight")
    while True:
        # Scroll down to bottom
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        #uncomment to limit the number of scrolls
        #scroll_number += 1
        # Wait to load page
        time.sleep(SCROLL_PAUSE_TIME)
        # Calculate new scroll height and compare with last scroll height
        new_height = driver.execute_script("return document.body.scrollHeight")
        if new_height == last_height:
            break
        last_height = new_height
    return

In [143]:
Job_post_date =[] 
company_name = []
job_title = []
job_links = []
Number_applicants = []
location = []
working_Place = []
def get_linkedin_jobs (soup):
    
    containers = soup.find_all(class_='jobs-search-results__list-item occludable-update p0 relative ember-view')
    for container in containers:
        try:              
            his=container.find(class_='job-card-container__listed-time job-card-container__footer-item')  
            Job_post_date.append(his.get_text(strip =True))
        except:
            Job_post_date.append('none')
        try:
            text=container.find(class_='job-card-container__link job-card-container__company-name ember-view')
            company_name.append(text.get_text(strip =True))
        except:
            company_name.append('none')
        try:
            desc=container.find(class_='disabled ember-view job-card-container__link job-card-list__title')
            job_title.append(desc.get_text(strip =True))
        except:
            job_title.append('none')  
        try:       
            desc=container.find(class_='disabled ember-view job-card-container__link job-card-list__title')
            descs = 'https://www.linkedin.com'+desc['href']
            job_links.append(descs)
        except:
            job_links.append('none')        

        try:        
            nb_applic=container.find(class_='job-card-container__applicant-count job-card-container__footer-item job-card-container__footer-item--highlighted t-bold inline-flex align-items-center')
            Number_applicants.append(nb_applic.get_text(strip= True))
        except:
            Number_applicants.append('none')

        try:        
            loca=container.find(class_='job-card-container__metadata-item')
            location.append(loca.get_text(strip= True))
        except:
            location.append('none')
        try:        
            working=container.find(class_='job-card-container__metadata-item job-card-container__metadata-item--workplace-type')
            working_Place.append(working.get_text(strip= True))
        except:
            working_Place.append('none')

In [162]:
company = input("Enter your value: ")
page = "https://www.linkedin.com/jobs/search/?geoId=105015875&keywords="+company+"%20jobs"
driver=webdriver.Chrome(r'C:\\Users\\jchih\\\Documents\\selenium\\chromedriver.exe')
driver.set_window_size(900,800)
connect_to_linkedin ()
for numb in range(10):
    sleep(1)
    driver.get(page+'&start='+str(numb*25)) 
    sleep(1)
    scrolling_function ()
    sleep(2)
    src =driver.page_source
    soup =BeautifulSoup(src, 'lxml')
    get_linkedin_jobs (soup)

Enter your value: accenture

In [163]:
jobs = pd.DataFrame(
        {'Job_post_date': Job_post_date,
         'company_name': company_name,
         'job_title': job_title, 
         "Number_applicants": Number_applicants,
         "Location": location,
         "working_Place": working_Place,
         "job_links":job_links,

        })

In [164]:
jobs

,Job_post_date,company_name,job_title,Number_applicants,Location,working_Place,job_links
0,2 weeks ago,Talan,Consultant(e) Data Analytics - H/F,11 applicants,"Aix-en-Provence, Provence-Alpes-Côte d'Azur, F...",none,https://www.linkedin.com/jobs/view/2982590168/...
1,2 weeks ago,Talan,Consultant(e) Data Analytics - H/F,5 applicants,"Lyon, Auvergne-Rhône-Alpes, France",none,https://www.linkedin.com/jobs/view/2982585736/...
2,1 day ago,Talan,Stage Big Data & Fullstack (H/F),none,"Paris, Île-de-France, France",On-site,https://www.linkedin.com/jobs/view/3012317480/...
3,2 weeks ago,Talan,Offreur Data Advisory,0 applicants,"Nantes, Pays de la Loire, France",On-site,https://www.linkedin.com/jobs/view/2982619017/...
4,4 weeks ago,Talan,Jeune Docteur Data Scientist H/F,none,"Paris, Île-de-France, France",On-site,https://www.linkedin.com/jobs/view/2964780365/...
...,...,...,...,...,...,...,...
190,2 weeks ago,Agoda,Analytics Manager- Partner Development,2 applicants,"Paris, Île-de-France, France",none,https://www.linkedin.com/jobs/view/2975177448/...
191,3 weeks ago,umlaut company,Web Developer,0 applicants,"Toulouse, Occitanie, France",On-site,https://www.linkedin.com/jobs/view/3014389707/...
192,2 months ago,Accenture France,Administrateur SCCM (F/H),4 applicants,"Paris, Île-de-France, France",On-site,https://www.linkedin.com/jobs/view/2910491007/...
193,2 weeks ago,Agoda,"Analyst/ Sr Analyst, Marketing (Bangkok Based,...",1 applicant,"Paris, Île-de-France, France",none,https://www.linkedin.com/jobs/view/2975682518/...
194,1 month ago,Accenture France,"Architecte Technique 3DExperience – Marseille,...",0 applicants,"Toulouse, Occitanie, France",none,https://www.linkedin.com/jobs/view/2962510387/...

for i in range(10):
    print(i*25)